kind: ConfigMap
apiVersion: v1
metadata:
  name: admin
  namespace: default
data:
  admin.greeting: test1
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: app
  namespace: default
data:
  base.url: test.local1
  service.environment: sit
---
kind: Secret
apiVersion: v1
metadata:
  name: appsecret
  namespace: default
data:
  db.secret: cGFzc2NoYW5nZQ==