name: build-verify-package
on:
  push:
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README*'
  pull_request:
    paths-ignore:
      - '.github/**'
      - '.gitignore'
      - 'LICENSE'
      - 'README*'

jobs:
  build-verify-package:
    runs-on: ubuntu-latest
    environment: Build
    steps:
      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Set up JDK 11 for x64
        uses: actions/setup-java@v2
        with:
          java-version: '11'
          distribution: 'adopt'
          architecture: x64
          cache: maven

      - name: Build Java components
        run: mvn -B clean install

      - name: Build Angular app
        run: |
          cd ${{github.workspace}}/webapp
          mvn -B -Pprod -DskipTests package

      - name: Run Integration tests
        run: |
          cd ${{github.workspace}}/webapp
          mvn -Pit test

      - name: Verify Javadoc completion
        run: mvn -B javadoc:javadoc

      - name: Set environment for branch
        run: |
          set -x
          if [[ $GITHUB_REF == 'refs/heads/master' ]]; then
            echo "IMAGE_TAG=latest" >> "$GITHUB_ENV"
            echo "PACKAGE_IMAGE=true" >> "$GITHUB_ENV"
          elif [[ $GITHUB_REF == 'refs/heads/1.5.x' ]]; then
            echo "IMAGE_TAG=nightly" >> "$GITHUB_ENV"
            echo "PACKAGE_IMAGE=true" >> "$GITHUB_ENV"
          elif [[ $GITHUB_REF == "refs/tags/$GITHUB_REF_NAME" ]]; then
            echo "IMAGE_TAG=$GITHUB_REF_NAME" >> "$GITHUB_ENV"
            echo "PACKAGE_IMAGE=true" >> "$GITHUB_ENV"
          else
            echo "PACKAGE_IMAGE=false" >> "$GITHUB_ENV"
          fi

      - name: Package container image for webapp
        if: github.repository_owner == 'microcks' && env.PACKAGE_IMAGE == 'true'
        run: |
          cd ${{github.workspace}}/webapp
          mvn -B -q -Pprod -DskipTests package docker:build;
          docker tag microcks/microcks quay.io/microcks/microcks:$IMAGE_TAG

      - name: Package container image for async minion
        if: github.repository_owner == 'microcks' && env.PACKAGE_IMAGE == 'true'
        run: |
          cd ${{github.workspace}}/minions/async
          mvn -B -q -DskipTests package
          docker build -f src/main/docker/Dockerfile.jvm -t quay.io/microcks/microcks-async-minion:$IMAGE_TAG .

      - name: Login and push to Quay.io Registry
        if: github.repository_owner == 'microcks' && env.PACKAGE_IMAGE == 'true'
        run: |
          echo ${{ secrets.QUAY_PASSWORD }} | docker login -u ${{ secrets.QUAY_USERNAME }} --password-stdin quay.io
          docker push quay.io/microcks/microcks:$IMAGE_TAG
          docker push quay.io/microcks/microcks-async-minion:$IMAGE_TAG