spring:
  application:
    name: admin
  cloud:
    kubernetes:
      config:
        enabled: true

server:
  servlet:
    context-path: /admin

admin.greeting: local

jwt:
  access.token:
    secret: w23pRF5mdn
    expiry: 99999
  refresh.token:
    expiry: 99999

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: always

management.health.circuitbreakers.enabled: true
management.health.ratelimiters.enabled: true



resilience4j.circuitbreaker:
  instances:
    peer:
      registerHealthIndicator: true
      slidingWindowSize: 5
      permittedNumberOfCallsInHalfOpenState: 3
      slidingWindowType: COUNT_BASED
      minimumNumberOfCalls: 5
      waitDurationInOpenState: 50s
      failureRateThreshold: 60
      eventConsumerBufferSize: 10
      slowCallRateThreshold: 50
      slowCallDurationThreshold: 2000