---
apiVersion: v1
kind: Namespace
metadata:
  name: microcks
  labels:
    app.kubernetes.io/name: microcks
    app.kubernetes.io/instance: microcks
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: microcks-config
  namespace: microcks
data:
  KEYCLOAK_ENABLED: "false"
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: microcks
    app.kubernetes.io/version: 1.0.0
  name: microcks
  namespace: microcks
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: microcks
    app.kubernetes.io/version: 1.0.0
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: microcks
    app.kubernetes.io/version: 1.0.0
  name: microcks
  namespace: microcks
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: microcks
      app.kubernetes.io/version: 1.0.0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: microcks
        app.kubernetes.io/version: 1.0.0
    spec:
      containers:
        - envFrom:
          - configMapRef:
              name: microcks-config
          image: microcks/microcks
          imagePullPolicy: IfNotPresent
          name: microcks
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app.kubernetes.io/name: microcks
    app.kubernetes.io/version: 1.0.0
  name: microcks
  namespace: microcks
spec:
  rules:
    - host: ""
      http:
        paths:
          - backend:
              service:
                name: microcks
                port:
                  name: http
            path: /microcks
            pathType: Prefix
