---
apiVersion: v1
kind: Namespace
metadata:
  name: mockswitch
  labels:
    app.kubernetes.io/name: mockswitch
    app.kubernetes.io/instance: mockswitch
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: mockswitch-config
  namespace: mockswitch
data:
  TEST: TEST
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: mockswitch
    app.kubernetes.io/version: 1.1.0
  name: mockswitch
  namespace: mockswitch
spec:
  ports:
    - name: http
      port: 80
      targetPort: 1025
  selector:
    app.kubernetes.io/name: mockswitch
    app.kubernetes.io/version: 1.1.0
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: mockswitch
    app.kubernetes.io/version: 1.1.0
  name: mockswitch
  namespace: mockswitch
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: mockswitch
      app.kubernetes.io/version: 1.1.0
  template:
    metadata:
      labels:
        app.kubernetes.io/name: mockswitch
        app.kubernetes.io/version: 1.1.0
    spec:
      containers:
        - envFrom:
          - configMapRef:
              name: mockswitch-config
          image: mockswitch/app
          imagePullPolicy: IfNotPresent
          name: mockswitch
          ports:
            - containerPort: 1025
              name: http
              protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app.kubernetes.io/name: mockswitch
    app.kubernetes.io/version: 1.1.0
  name: mockswitch
  namespace: mockswitch
spec:
  rules:
    - host: ""
      http:
        paths:
          - backend:
              service:
                name: mockswitch
                port:
                  name: http
            path: /mockswitch
            pathType: Prefix
