---
apiVersion: v1
kind: Namespace
metadata:
  name: redis
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/instance: redis
---
kind: ConfigMap
apiVersion: v1
metadata:
  name: redis-config
  namespace: redis
data:
  REDISINSIGHT_BASEPATH: redis
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: 6.2.6
  name: redis
  namespace: redis
spec:
  ports:
    - name: http
      port: 6379
      targetPort: 6379
  selector:
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: 6.2.6
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: redis
    app.kubernetes.io/version: 6.2.6
  name: redis
  namespace: redis
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: redis
      app.kubernetes.io/version: 6.2.6
  template:
    metadata:
      labels:
        app.kubernetes.io/name: redis
        app.kubernetes.io/version: 6.2.6
    spec:
      containers:
        - envFrom:
          - configMapRef:
              name: redis-config
          image: redis:6.2.6
          imagePullPolicy: IfNotPresent
          name: redis
          ports:
            - containerPort: 6379
              name: http
              protocol: TCP
