---
apiVersion: v1
kind: Service
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    app.dekorate.io/vcs-url: <<unknown>>
    app.dekorate.io/commit-id: e90a95b4de97dcd6cba418f9d28162924d496ef7
  labels:
    app.kubernetes.io/name: admin
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  name: admin
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app.kubernetes.io/name: admin
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    app.dekorate.io/vcs-url: <<unknown>>
    app.dekorate.io/commit-id: e90a95b4de97dcd6cba418f9d28162924d496ef7
  labels:
    app.kubernetes.io/name: admin
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  name: admin
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: admin
      app.kubernetes.io/version: 0.0.1-SNAPSHOT
  template:
    metadata:
      annotations:
        kubernetes.io/ingress.class: nginx
        app.dekorate.io/vcs-url: <<unknown>>
        app.dekorate.io/commit-id: e90a95b4de97dcd6cba418f9d28162924d496ef7
      labels:
        app.kubernetes.io/name: admin
        app.kubernetes.io/version: 0.0.1-SNAPSHOT
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: kathiravan88/admin
          imagePullPolicy: IfNotPresent
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /admin/actuator/info
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
          name: admin
          ports:
            - containerPort: 8080
              name: http
              protocol: TCP
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /admin/actuator/health
              port: 8080
              scheme: HTTP
            initialDelaySeconds: 0
            periodSeconds: 30
            successThreshold: 1
            timeoutSeconds: 10
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
    app.dekorate.io/vcs-url: <<unknown>>
    app.dekorate.io/commit-id: e90a95b4de97dcd6cba418f9d28162924d496ef7
  labels:
    app.kubernetes.io/name: admin
    app.kubernetes.io/version: 0.0.1-SNAPSHOT
  name: admin
spec:
  rules:
    - host: ""
      http:
        paths:
          - backend:
              service:
                name: admin
                port:
                  name: http
            path: /admin
            pathType: Prefix
