---
apiVersion: v1
kind: Service
metadata:
  labels:
    app.kubernetes.io/name: ui-app1
    app.kubernetes.io/version: 0.0.1
  name: ui-app1
spec:
  ports:
    - name: http
      port: 80
      targetPort: 3000
  selector:
    app.kubernetes.io/name: ui-app1
    app.kubernetes.io/version: 0.0.1
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app.kubernetes.io/name: ui-app1
    app.kubernetes.io/version: 0.0.1
  name: ui-app1
spec:
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: ui-app1
      app.kubernetes.io/version: 0.0.1
  template:
    metadata:
      labels:
        app.kubernetes.io/name: ui-app1
        app.kubernetes.io/version: 0.0.1
    spec:
      containers:
        - env:
            - name: KUBERNETES_NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
          image: kathiravan88/ui-app1
          imagePullPolicy: IfNotPresent
          name: ui-app1
          ports:
            - containerPort: 3000
              name: http
              protocol: TCP
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  annotations:
    kubernetes.io/ingress.class: nginx
  labels:
    app.kubernetes.io/name: ui-app1
    app.kubernetes.io/version: 0.0.1
  name: ui-app1
spec:
  rules:
    - host: ""
      http:
        paths:
          - backend:
              service:
                name: ui-app1
                port:
                  name: http
            path: /ui-app1
            pathType: Prefix


    # nginx.ingress.kubernetes.io/rewrite-target: /$2
    
    #         path: /ui-app1(/|$)(.*)