apiVersion: skaffold/v2beta26
kind: Config
metadata:
  name: ui-app1
build:
  artifacts:
  - image: kathiravan88/ui-app1
    docker:
      dockerfile: Dockerfile
deploy:
  kubectl:
    manifests:
    - kubernetes.yml
